<script>
	$(document).ready(function(){
		//alert();
			$(".emoji_1").each(function(){
			$(this).find("li").on({
				click:function(){
					e=$(this).html();
					document.getElementById("chatting_box").value+=e;
				}
			});
		});
			
		$(".emoji_2").each(function(){
			$(this).find("li").on({
				click:function(){
					e=$(this).html();
					document.getElementById("chatting_box").value+=e;
				}
			});
		});
	});
</script>
<div class="text_box" id='group_chat_typerB'>
				<textarea placeholder="Type your message..." spellcheck="false" contenteditable="true" id='chatting_box' onkeypress="sendGroupTypedMessage(event,this)"></textarea>
				<div class="emoji_icon" onclick="groupchatemoji()">
					<i class="ion-android-happy"></i>
				</div>
				<div class="emoji_box">
					<div class="emoji_pointer"></div>
					<div class="emoji_pannel">
						<ul>
							<div class="emoji_1">
								<li>😀</li>
								<li>😃</li>
								<li>😄</li>
								<li>😁</li>
								<li>😆</li>
								<li>😅</li>
								<li>😂</li>
								<li>😊</li>
								<li>😇</li>
								<li>😝</li>
								<li>😛</li>
								<li>😎</li>
								<li>😏</li>
								<li>😒</li>
								<li>😞</li>
								<li>😔</li>
								<li>😟</li>
								<li>😕</li>
								<li>🙂</li>
								<li>😉</li>
								<li>😌</li>
								<li>😍</li>
								<li>😘</li>
								<li>😗</li>
								<li>😙</li>
								<li>😚</li>
								<li>😋</li>
								<li>😜</li>
								<li>🙁</li>
								<li>😣</li>
								<li>😖</li>
								<li>😫</li>
								<li>😩</li>
								<li>😤</li>
								<li>😡</li>
								<li>😶</li>
								<li>😐</li>
								<li>😯</li>
								<li>😦</li>
								<li>😧</li>
								<li>😮</li>
								<li>😲</li>
								<li>😵</li>
								<li>😳</li>
								<li>😱</li>
								<li>😨</li>
								<li>😰</li>
								<li>😢</li>
								<li>😥</li>
								<li>😭</li>
								<li>😬</li>
								<li>😓</li>
								<li>😪</li>
								<li>😴</li>
								<li>😷</li>
								<li>😈</li>
								<li>👿</li>
								<li>👹</li>
								<li>👺</li>
								<li>💩</li>
								<li>👻</li>
								<li>💀</li>
								<li>👽</li>
								<li>👾</li>
								<li>🎃</li>
								<li>☠</li>
								<li>😿</li>
								<li>😾</li>
								<li>🙌</li>
								<li>🙏</li>
								<li>👊</li>
								<li>👱</li>
								<li>👴</li>
								<li>👵</li>
								<li>👲</li>
								<li>👳‍</li>
								<li>👮</li>
								<li>👷</li>
								<li>💂</li>
								<li>🎅</li>
								<li>👸</li>
								<li>👰</li>
								<li>🙇</li>
								<li>🙅</li>
								<li>🙆</li>
								<li>🙋</li>
								<li>🙍</li>
								<li>💆</li>	
								<li>👯</li>
							</div>
						<div class="emoji_2">
							<li>🐶</li>
							<li>🐱</li>
							<li>🐭</li>
							<li>🐹</li>
							<li>🐰</li>
							<li>🐻</li>
							<li>🐼</li>
							<li>🐨</li>
							<li>🐯</li>
							<li>🐮</li>
							<li>🐷</li>
							<li>🐽</li>
							<li>🐸</li>
							<li>🐵</li>
							<li>🙊</li>
							<li>🙉</li>
							<li>🙊</li>
							<li>🐒</li>
							<li>🐔</li>
							<li>🐧</li>
							<li>🐦</li>
							<li>🐤</li>
							<li>🐣</li>
							<li>🐥</li>
							<li>🐺</li>
							<li>🐗</li>
							<li>🐴</li>
							<li>🐝</li>
							<li>🐛</li>
							<li>🐌</li>
							<li>🐚</li>
							<li>🐞</li>
							<li>🐜</li>
							<li>🕷</li>
							<li>🕸</li>
							<li>🐢</li>
							<li>🐍</li>
							<li>🐙</li>
							<li>🐠</li>
							<li>🐟</li>
							<li>🐡</li>
							<li>🐬</li>
							<li>🐳</li>
							<li>🐋</li>
							<li>🐊</li>
							<li>🐆</li>
							<li>🐅</li>
							<li>🐃</li>
							<li>🐂</li>
							<li>🐄</li>
							<li>🐪</li>
							<li>🐘</li>
							<li>🐎</li>
							<li>🐖</li>
							<li>🐐</li>
							<li>🐏</li>
							<li>🐑</li>
							<li>🐩</li>
							<li>🐓</li>
							<li>🐇</li>
							<li>🐀</li>
							<li>🐉</li>
							<li>🌞</li>
							<li>☃</li>
							<li>🌫</li>
							<li>🌊</li>
							<li>🌤</li>
							<li>🎍</li>
							<li>🐾</li>
							<li>🐇</li>
						</div>
						</ul>
					</div>
					<div class="emoji_item">
						<ul>
							<li><img src="../images/1.png" onclick="emojiIcon1(1)"></li>
							<li><img src="../images/(6).png" onclick="emojiIcon1(2)"></li>
						</ul>
					</div>
				</div>
			</div>